#!/usr/bin/env bash
# compare-godoc.sh — Side-by-side godoc comparison between docs/coverage-v2
# (HEAD) and docs/godoc-coverage (v1 reference branch).
#
# Backs the v2 rollout's per-layer reviewability workflow: for each Go
# package in the named layer, run `go doc -all` on both branches, diff the
# output, and emit a markdown report at docs/coverage-v2-comparison/<layer>.md
# for the human or AI reviewer to classify.
#
# Usage:
#   scripts/compare-godoc.sh <layer-name>
#
# Layers are defined in scripts/compare-godoc-layers.txt. The v1 reference
# is checked out as a git worktree at ../zenon-v1-ref the first time the
# script runs.

set -euo pipefail

LAYER="${1:?usage: compare-godoc.sh <layer-name>}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

V1_REF="origin/docs/godoc-coverage"
V1_WORKTREE="$(cd .. && pwd)/zenon-v1-ref"
OUT_DIR="docs/coverage-v2-comparison"
OUT_FILE="$OUT_DIR/$LAYER.md"
LAYERS_CONF="scripts/compare-godoc-layers.txt"

# Resolve packages for the layer.
PKGS=$(awk -F: -v l="$LAYER" '!/^#/ && !/^$/ && $1==l{print $2}' "$LAYERS_CONF")
if [ -z "$PKGS" ]; then
  echo "error: layer '$LAYER' not found in $LAYERS_CONF" >&2
  echo "known layers:" >&2
  awk -F: '!/^#/ && !/^$/ && NF>=2{print "  " $1}' "$LAYERS_CONF" >&2
  exit 2
fi

# Ensure the v1 reference worktree exists. The worktree lives outside the
# repo so it does not pollute git status. If origin/docs/godoc-coverage
# is missing locally, `git fetch origin` first.
if [ ! -d "$V1_WORKTREE" ]; then
  echo "Creating worktree at $V1_WORKTREE pinned to $V1_REF..."
  git worktree add "$V1_WORKTREE" "$V1_REF"
fi

mkdir -p "$OUT_DIR"

HEAD_SHORT="$(git rev-parse --short HEAD)"
HEAD_BRANCH="$(git symbolic-ref --short HEAD 2>/dev/null || echo "(detached)")"
V1_SHORT="$(git -C "$V1_WORKTREE" rev-parse --short HEAD)"

write_report() {
  echo "# v1 vs v2 godoc comparison — $LAYER"
  echo
  echo "Generated by \`scripts/compare-godoc.sh $LAYER\`."
  echo
  echo "| Side | Branch | Commit | Worktree |"
  echo "|------|--------|--------|----------|"
  echo "| v1   | \`$V1_REF\` | \`$V1_SHORT\` | \`$V1_WORKTREE\` |"
  echo "| v2   | \`$HEAD_BRANCH\` | \`$HEAD_SHORT\` | \`$ROOT\` |"
  echo
  echo "Per-package diff of \`go doc -all <pkg>\`. Classify each diff hunk:"
  echo
  echo "- **Match** — different wording, same meaning. No action."
  echo "- **v2 adds** — v2 covers something v1 missed. Confirm correct."
  echo "- **v1 had** — v1 covered something v2 omitted. Either add to v2 or justify omission."
  echo "- **CONFLICT** — v1 and v2 make different technical claims. Read code, correct the wrong side."
  echo
  echo "All CONFLICT entries must be resolved (with rationale below the diff) before opening the layer PR."
  echo
  echo "---"
  echo

  IFS=',' read -ra PKG_ARR <<< "$PKGS"
  for PKG in "${PKG_ARR[@]}"; do
    PKG="$(echo "$PKG" | tr -d '[:space:]')"
    [ -z "$PKG" ] && continue

    echo "## \`$PKG\`"
    echo

    V1_OUT=$(mktemp)
    V2_OUT=$(mktemp)

    if ! GOWORK=off go doc -all "$PKG" > "$V2_OUT" 2>&1; then
      echo "_v2 \`go doc -all\` failed:_"
      echo
      echo '```'
      cat "$V2_OUT"
      echo '```'
      echo
      rm -f "$V1_OUT" "$V2_OUT"
      continue
    fi

    if ! (cd "$V1_WORKTREE" && GOWORK=off go doc -all "$PKG") > "$V1_OUT" 2>&1; then
      echo "_v1 \`go doc -all\` failed (package may not exist on v1):_"
      echo
      echo '```'
      cat "$V1_OUT"
      echo '```'
      echo
      echo "Treating entire package as **v2 adds**."
      echo
      rm -f "$V1_OUT" "$V2_OUT"
      continue
    fi

    if cmp -s "$V1_OUT" "$V2_OUT"; then
      echo "**Match.** v1 and v2 emit byte-identical \`go doc -all\` output."
      echo
    else
      V1_LINES=$(wc -l < "$V1_OUT" | tr -d ' ')
      V2_LINES=$(wc -l < "$V2_OUT" | tr -d ' ')
      DIFF_LINES=$(diff -u "$V1_OUT" "$V2_OUT" | wc -l | tr -d ' ' || true)
      echo "v1: $V1_LINES lines · v2: $V2_LINES lines · diff: $DIFF_LINES lines"
      echo
      echo '<details><summary>Diff (v1 → v2)</summary>'
      echo
      echo '```diff'
      diff -u "$V1_OUT" "$V2_OUT" || true
      echo '```'
      echo
      echo '</details>'
      echo
      echo "**Classification** (check exactly one or annotate per-hunk):"
      echo
      echo "- [ ] Match — wording only"
      echo "- [ ] v2 adds — justified additions"
      echo "- [ ] v1 had — symbols/wording missing from v2 (resolution: _fill in_)"
      echo "- [ ] CONFLICT — divergent technical claims (resolution: _fill in_)"
      echo
    fi

    rm -f "$V1_OUT" "$V2_OUT"
  done
}

write_report > "$OUT_FILE"

echo "Wrote $OUT_FILE"
