name: Build and release znnd and libznn

on:
  push:
    branches:
      - cicd
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install zip utility
        run: |
          sudo apt update
          sudo apt install -y zip
      - name: Run tests
        run: |
          go test ./...
      - name: Check for Go vulnerabilities
        uses: opzkit/govulncheck-action@v1.0.0
        with:
          govuln-version: 'latest'
          packages: './...'
      - name: Make version
        run: make version
      - name: Build znnd
        uses: crazy-max/ghaction-xgo@v2.3.0
        with:
          xgo_version: latest
          go_version: latest
          dest: build
          prefix: znnd
          pkg: cmd/znnd
          targets: darwin/arm64,darwin/amd64,windows/amd64,linux/amd64,linux/arm64
          v: true
          x: true
          ldflags: -s -w
          buildvcs: false
          buildmode: default
          trimpath: true
      - name: Build libznn
        uses: crazy-max/ghaction-xgo@v2.3.0
        with:
          xgo_version: latest
          go_version: latest
          dest: build
          prefix: libznn
          pkg: cmd/libznn
          targets: darwin/arm64,darwin/amd64,windows/amd64,linux/amd64,linux/arm64
          v: true
          x: true
          tags: libznn
          ldflags: -s -w
          buildvcs: false
          buildmode: c-shared
          trimpath: true
      - name: Run makefat for darwin builds
        run: |
          cd ..
          git clone https://github.com/randall77/makefat.git
          cd makefat/
          go build -o mainfat makefat.go
          ./mainfat ../go-zenon/build/libznn-darwin-universal.dylib ../go-zenon/build/libznn-darwin-amd64.dylib ../go-zenon/build/libznn-darwin-arm64.dylib
          ./mainfat ../go-zenon/build/znnd-darwin-universal ../go-zenon/build/znnd-darwin-amd64 ../go-zenon/build/znnd-darwin-arm64
      - name: Go back to build directory, remove header files and add execute flag
        run: |
          cd build/
          rm ./*.h
          chmod +x ./*
      - name: Archive files
        run: |
          cd build/
          for file in *windows*; do zip $(echo $file | rev | cut -d '.' -f2- | rev)".zip" "$file" && rm "$file" ; done && for so in "linux" "darwin"; do for file in *"$so"*; do tar cvzf $(echo $file | rev | cut -d '.' -f2- | rev)".tar.gz" "$file" && rm "$file" ; done; done
      - name: Generate checksums
        run: | 
          cd build/
          sha256sum * > SHA256CHECKSUMS.txt
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
          body: ""
