on:
  push:
    branches:
      - cicd
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Go vulnerabilities
        uses: opzkit/govulncheck-action@v1.0.0
        with:
          govuln-version: 'latest'
          packages: './...'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build znnd
        uses: crazy-max/ghaction-xgo@v2.2.0
        with:
          xgo_version: latest
          go_version: latest
          dest: build
          prefix: znnd
          pkg: cmd/znnd
          targets: darwin/arm64,darwin/amd64,windows/amd64,linux/amd64,linux/arm64
          v: false
          x: false
          ldflags: -s -w
          buildvcs: true
          buildmode: default
          trimpath: true
      - name: Build libznn
        uses: crazy-max/ghaction-xgo@v2.2.0
        with:
          xgo_version: latest
          go_version: latest
          dest: build
          prefix: libznn
          pkg: cmd/libznn
          targets: darwin/arm64,darwin/amd64,windows/amd64,linux/amd64,linux/arm64
          v: false
          x: false
          ldflags: -s -w
          buildvcs: true
          buildmode: c-shared
          trimpath: true
      - name: Run makefat for darwin builds
        run: cd .. && git clone https://github.com/randall77/makefat.git && cd ./makefat && go build -o mainfat makefat.go && ./mainfat ../go-zenon/build/libznn.dylib ../go-zenon/build/libznn-darwin-amd64.dylib ../go-zenon/build/libznn-darwin-arm64.dylib && ./mainfat ../go-zenon/build/znnd-darwin-universal ../go-zenon/build/znnd-darwin-amd64 ../go-zenon/build/znnd-darwin-arm64 && ls -alh ../go-zenon/build/
      - name: Go back to build directory and remove header files
        run: pwd && cd ./build && rm ./*.h
      - name: Generate SHA256 checksum
        run: cd build/ && sha256sum * > SHA256CHECKSUMS.txt
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          body: "Test release"